# services:
#   # e-store-discovery-service:
#   #   build: ./discovery-service
#   #   container_name: e-store-discovery-service
#   #   ports:
#   #     - '8761:8761'
#   #   expose:
#   #     - '8761'
#   #   healthcheck:
#   #     test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
#   #     interval: 10s
#   #     retries: 4

#   # e-store-config-service:
#   #   build: ./config-service
#   #   container_name: e-store-config-service
#   #   ports:
#   #     - '9999:9999'
#   #   expose:
#   #     - '9999'
#   #   environment:
#   #     - DISCOVERY_SERVICE_URL=http://e-store-discovery-service:8761/eureka
#   #   healthcheck:
#   #     test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
#   #     interval: 10s
#   #     retries: 4
#   #   depends_on:
#   #     e-store-discovery-service:
#   #       condition: service_healthy

#   # e-store-rabbitmq:
#   #   image: "rabbitmq:management"
#   #   ports:
#   #     - "5672:5672"
#   #     - "15672:15672"

#   # e-store-product-service:
#   #   build: ./product-service
#   #   ports:
#   #     - '8060'
#   #   environment:
#   #     - DISCOVERY_SERVICE_URL=http://e-store-discovery-service:8761/eureka
#   #     - CONFIG_SERVICE_URL=http://e-store-config-service:9999
#   #   healthcheck:
#   #     test: [ "CMD", "curl", "-f", "http://localhost:8060/actuator/health" ]
#   #     interval: 10s
#   #   depends_on:
#   #     e-store-config-service:
#   #       condition: service_healthy
#   #   deploy:
#   #     replicas: 2

#   # e-store-client-service:
#   #   build: ./client-service
#   #   container_name: e-store-client-service
#   #   ports:
#   #     - '8050:8050'
#   #   expose:
#   #     - '8050'
#   #   environment:
#   #     - DISCOVERY_SERVICE_URL=http://e-store-discovery-service:8761/eureka
#   #     - CONFIG_SERVICE_URL=http://e-store-config-service:9999
#   #   healthcheck:
#   #     test: [ "CMD", "curl", "-f", "http://localhost:8050/actuator/health" ]
#   #     interval: 10s
#   #   depends_on:
#   #     e-store-product-service:
#   #       condition: service_healthy

#   # e-store-sales-service:
#   #   build: ./sales-service
#   #   container_name: e-store-sales-service
#   #   ports:
#   #     - '8070:8070'
#   #   expose:
#   #     - '8070'
#   #   environment:
#   #     - DISCOVERY_SERVICE_URL=http://e-store-discovery-service:8761/eureka
#   #     - CONFIG_SERVICE_URL=http://e-store-config-service:9999
#   #   depends_on:
#   #     e-store-client-service:
#   #       condition: service_healthy

#   # e-store-gateway-service:
#   #   build: ./gateway-service
#   #   container_name: e-store-gateway-service
#   #   ports:
#   #     - '8888:8888'
#   #   expose:
#   #     - '8888'
#   #   environment:
#   #     - DISCOVERY_SERVICE_URL=http://e-store-discovery-service:8761/eureka
#   #     - CONFIG_SERVICE_URL=http://e-store-config-service:9999
#   #   depends_on:
#   #     e-store-config-service:
#   #       condition: service_healthy

#   # e-store-reactapp:
#   #   build: ./e-store-react-app
#   #   container_name: e-store-reactapp
#   #   ports:
#   #     - '5173:5173'
#   #   expose:
#   #     - '5173'
#   #   depends_on:
#   #     e-store-product-service:
#   #       condition: service_healthy
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  keycloak:
      image: quay.io/keycloak/keycloak
      environment:
        KEYCLOAK_ADMIN: tahaadmin
        KEYCLOAK_ADMIN_PASSWORD: taha
      command: [ "start-dev", "--import-realm" ]
      volumes:
            - ./realm/:/opt/keycloak/data/import/
      ports:
        - "8080:8080"
